analysis:
    nbins: 4
    nside: 256 
    sigma_e: 0.261
    pixwin: /path/to/files/pixwin.npy

io:     
    datafile: /path/to/files/desy3_shear_data.h5
    io_dir: /path/to/files/io_dir/
    maskfile: /path/to/files/mask_desy3.fits
    x_init_file: /path/to/files/kappa_MAP.h5
    store_fields: true
    
mcmc:
    n_burn_in: 200
    n_samples: 200
    step_size: 0.2
    
cosmology:
    td_file: /path/to/files/training_data.h5
    priors:
    - {type: uniform}                           # Om, uses emulator bounds automatically
    - {type: gaussian, mu: 0.82, sigma: 0.04}   # S8
    - {type: uniform, low: -2.0, high: -0.33}   # w manual override of bounds
    - {type: deterministic, value: 0.02237}     # ob
    - {type: gaussian, mu: 0.70, sigma: 0.05}   # h
    - {type: uniform}                           # ns
mocks:
    #(Omega_m, S8, w, omegab, h, ns)
    N_theta: 6
    theta_fid: 0.279798753,0.87134582355,-1.0721294206,0.02237,0.7022,0.9649
    N_map: data/des_y3/N.npy
