analysis:
    nbins: 4
    nside: 256 
    sigma_e: 0.261
    shift: 0.00416708,0.0085054,0.01561475,0.0236787 
    vargauss: 0.18815055,0.14421919,0.1114475,0.06784224
    cl_file: data/des_y3/cl.npy
    pixwin: data/healpix/hybrid_pixwin_256.npy

io:     
    datafile: data/des_y3/desy3_shear_data.h5
    io_dir: output/des_y3/
    maskfile: data/des_y3/mask_desy3.fits
     
mcmc:
    n_burn_in: 150
    n_samples: 100
    
