analysis:
    nbins: 4
    nside: 256 
    sigma_e: 0.261
    shift: 0.00416708,0.0085054,0.01561475,0.0236787 
    vargauss: 0.18815055,0.14421919,0.1114475,0.06784224
    cl_file: data/des_y3/cl.npy
    pixwin: data/healpix/hybrid_pixwin_256.npy

io:     
    datafile: data/des_y3/desy3_shear_data.h5
    io_dir: output/des_y3_cosmo
    maskfile: data/des_y3/mask_desy3.fits
    x_init_file: output/des_y3/kappa_MAP.h5
    
mcmc:
    n_burn_in: 200
    n_samples: 200
    step_size: 0.2
    custom_mass_matrix: true
    
cosmology:
    shift_file: data/des_y3/shift_training_data.pt
    mean_g_file: data/des_y3/mean_g_training_data.pt
    y_cl_file: data/des_y3/ycl_training_data.pt

mocks:
    #(Omega_m, sigma8, w, omegab, h, ns)
    N_theta: 6
    theta_fid: 0.279798753,0.87134582355,-1.0721294206,0.02237,0.7022,0.9649
