analysis:
    nbins: 4
    nside: 256 
    sigma_e: 0.261
    pixwin: /path/to/files/pixwin_Nside_256.npy

io:     
    datafile: /path/to/files/data.h5
    io_dir: /path/to/files/iodir/
    maskfile: /path/to/files/mask.npy
    x_init_file: /path/to/files/kappa_MAP.h5
    store_fields: False

mcmc:
    n_burn_in: 200
    n_samples: 200
    step_size: 0.2
    
cosmology:
    td_file: /path/to/files/training_data.h5
    priors:
    - {name: Om, type: uniform, low: 0.20359217, high: 0.39844121}  
    - {name: S8, type: uniform, low: 0.50505274, high: 0.99521593}   
    - {name: w, type: uniform, low: -1.4411547, high: -0.50430316} 
    - {name: ob, type: uniform, low: 0.02251592, high: 0.02255948} 
    - {name: h, type: uniform, low: 0.68756442, high: 0.69468036}   
    - {name: ns, type: uniform, low: 0.96144956, high: 0.9631907}   

multiplicative_bias:
    - {bin: 0, type: gaussian, mu: 0.0, sigma: 0.01}
    - {bin: 1, type: gaussian, mu: 0.0, sigma: 0.01}
    - {bin: 2, type: gaussian, mu: 0.0, sigma: 0.01}
    - {bin: 3, type: gaussian, mu: 0.0, sigma: 0.01}

mocks:
    theta_fid:
        Om: 0.2829817
        S8: 0.71783496
        w: -1.12658471
        ob: 0.0225377
        h: 0.69112239
        ns: 0.96232013
    mb_init: [0.0, 0.0, 0.0, 0.0]
    N_map: /path/to/files/N.npy
